### ISSUE TITLE
Research - Diet

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#6]
In order to better understand how people can impact the earth and create a greener tomorrow we must understand dietary impact.

Research the effect of diet (Vegan, Veggie, localshopping etc) and what impact it has. We will create a basic algo for determining percentage of 1-100 based on these calculations.

**Comment by AMJL-16** [comment]
2. 
Research on diet part, it is a general overview of the subject.
Should we narrow it to only Ireland ?


1. Meat-heavy Diet:

Carbon Footprint:  
High greenhouse gas (GHG) emissions. Beef and lamb, in particular, have the highest emissions per kilogram.

Land Use:
Requires significant amounts of land for grazing and growing feed crops.

Water Use:
High, especially for beef due to the water required to grow feed crops.

Biodiversity:
Grazing and feed crop production can contribute to deforestation, impacting biodiversity. Overfishing is also a concern for those consuming large amounts of fish.

2. Omnivore (Balanced meat and plant intake):

Carbon Footprint:
Moderate GHG emissions, though still significant if red meats are regularly consumed.

Land Use:
Mixed. Still requires land for animal agriculture, but less than a meat-heavy diet.

Water Use:
Moderate. Again, red meat consumption can significantly drive up water use.

Biodiversity:
Some impact due to a mix of plant and animal agriculture, but less than meat-heavy diets.

3. Pescatarian (Fish and plants, no land animals):

Carbon Footprint:
Lower than omnivorous, but emissions from fishery activities can still be notable.

Land Use:
Reduced compared to diets involving land animals.

Water Use:
Moderate. Aquaculture (fish farming) can consume significant water, but less than cattle farming.

Biodiversity:
Concerns about overfishing and its impact on marine ecosystems.

4. Vegetarian (Plants, dairy, eggs, no meat):

Carbon Footprint:
Lower than pescatarian and omnivorous diets, but dairy production, particularly, can contribute to GHG emissions.

Land Use:
Mixed. Dairy farming requires land for grazing and feed crops but generally less than meat production.

Water Use:
Reduced, especially if the diet is low in dairy products.

Biodiversity:
Dairy farming can impact land use and contribute to deforestation, but less so than meat-heavy diets.

5. Vegan (Only plant-based foods):

Carbon Footprint:
Typically the lowest among the diets mentioned here.

Land Use:
Primarily for crops. Significantly less than diets involving animal agriculture.

Water Use:
Generally lower, though it depends on the specific plant foods consumed (e.g., almonds require a lot of water).

Biodiversity:
Potentially beneficial if it leads to reduced land conversion for agriculture. However, large-scale monocultures can also impact biodiversity.

6. Local Shopping (Regardless of diet):

Carbon Footprint:
Reduced due to fewer transportation emissions. The actual reduction depends on how far food typically travels to reach the consumer.

Land Use and Water Use:
Not significantly different unless local farms use more sustainable practices.

Biodiversity:
Potentially beneficial if local farms practice biodiversity-friendly farming.

Conclusion, plant-based diets typically have the lowest environmental impact. However, it's not just the type of diet but also the sourcing, production methods, and other nuances that play a role in its overall environmental footprint.

**Comment by AMJL-16** [comment]
based on some research, here is an estimate of each diet for Ireland:

Meat-heavy Diet => around 7.2 kg CO2 per day per person.
Omnivore Diet         =>         5.8 kg CO2 per day per person.
Pescatarian Diet       =>         4.5 kg CO2 per day per person.
Vegetarian Diet        =>         3.8 kg CO2 per day per person.
Vegan Diet               =>         2.9 kg CO2 per day per person.

Also, if you shop local you get a 10% (or more )of your score for reducing your carbon Footprint.

calculation based on a max consumption of  Meat-heavy Diet of 7.2 kg 

Meat-heavy Diet gives you the highest carbon footprint score of 100 % .
So based on that : 

Omnivore: 
5.8 / 7.2 × 100 = 80.5 %

Pescatarian: 
4.5 / 7.2 × 100 = 62.5 %

Vegetarian: 
3.8 / 7.2 ×100 = 52.7 %

Vegan: 
2.9 / 7.2 × 100 = 40.2 %

Adjusted calculation If local shopping, reduce score by 10% which gives you: 
if we take vegan : 2.9 / 7.2 x 100 = 40.2 x 0.9 = 36.18 %
